export const createMockTicket = (overrides = {}) => ({
  id: 'TKT-0001',
  title: 'Sample Ticket',
  category: 'General',
  priority: 'Low' as const,
  location: 'Office',
  estimatedCost: 0,
  description: 'Mock description',
  tags: [],
  status: 'pending_hr' as const,
  createdBy: 'u-helpdesk',
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
  assignee: null,
  inspection: null,
  payment: null,
  pdfs: [],
  comments: [],
  signatures: {},
  ...overrides,
});
